name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    outputs:
      release_body: ${{ steps.release.outputs.RELEASE_BODY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v2.0.6
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip all
        env:
          OUTPUT: CHANGES.md

      - name: Set the release body
        id: release
        shell: bash
        run: |
          r=$(cat ${{ steps.git-cliff.outputs.changelog }})
          r="$(printf "$r" | tail -n +3)"
          r="${r//'%'/'%25'}"     # Multiline escape sequences for %
          r="${r//$'\n'/'%0A'}"   # Multiline escape sequences for '\n'
          r="${r//$'\r'/'%0D'}"   # Multiline escape sequences for '\r'
          echo "::set-output name=RELEASE_BODY::$r"

  # use release body in another job
  publish:
    name: Publish on the GitHub
    needs: changelog
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Create a new GitHub release using the gathered information
      - name: Create the release
        uses: nekofar/create-github-release@v1.0.0
        with:
          token: ${{ github.token }} # Authentication token from GitHub
          tag: ${{ github.ref_name }} # The name of the tag to be released
          title: ${{ github.ref_name }} # The title for the release
          notes: ${{ needs.changelog.outputs.release_body }} # The release notes generated in the previous step
          prerelease: ${{ contains(github.ref_name, ('-rc' or '-beta' or '-alpha')) }} # Conditions to mark the release as a pre-release
